export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background py-12 px-4">
      <div className="max-w-4xl mx-auto bg-card border-4 border-foreground brutalist-shadow-lg p-8">
        <h1 className="text-3xl font-black mb-6">Prometheus AI – Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-6">Effective Date: October 6, 2025</p>

        <div className="space-y-6 text-sm leading-6">
          <section>
            <h2 className="font-black text-lg mb-2">1. Description of the Service</h2>
            <p>
              Prometheus AI (“the Service”) is an AI-powered chatbot project created by independent developers. It is designed to provide
              unfiltered, blunt conversations around political, ethical, and societal topics. The chatbot generates responses based on user
              prompts using machine learning models.
            </p>
            <p className="mt-2">
              The Service is offered for informational, entertainment, and exploratory purposes only. It is not professional advice (legal,
              medical, financial, or otherwise) and should not be relied upon for decision-making. Responses may include hypothetical,
              opinionated, or controversial viewpoints, which may not reflect factual information.
            </p>
          </section>

          <section>
            <h2 className="font-black text-lg mb-2">2. Eligibility</h2>
            <p>
              You must be at least 18 years old (or the age of majority in your jurisdiction) to use Prometheus AI. By accessing or using the
              Service, you represent that you meet this requirement and are not prohibited from using the Service under applicable laws.
            </p>
          </section>

          <section>
            <h2 className="font-black text-lg mb-2">3. User Accounts</h2>
            <p>Some features of the Service may require you to create an account. By doing so, you agree to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Provide accurate and complete information.</li>
              <li>Keep your login details secure.</li>
              <li>Notify us immediately of any unauthorized use of your account.</li>
            </ul>
            <p className="mt-2">
              You are solely responsible for activity under your account. We may suspend or terminate accounts that violate these Terms.
            </p>
          </section>

          <section>
            <h2 className="font-black text-lg mb-2">4. Acceptable Use</h2>
            <p>You agree to use the Service responsibly and for lawful purposes. You must not:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Submit content that infringes intellectual property or privacy rights.</li>
              <li>Post or share illegal, abusive, hateful, or harmful content.</li>
              <li>Attempt to bypass safety mechanisms (e.g., prompt injection, jailbreaking).</li>
              <li>
                Use the Service to impersonate others, spread misinformation, or interfere with elections without proper disclosure.
              </li>
              <li>Enter sensitive personal data or use outputs for high-risk decisions.</li>
              <li>Reverse-engineer, scrape, or attempt to disrupt the Service.</li>
            </ul>
            <p className="mt-2">
              We may monitor usage and remove or block content that violates these Terms. Outputs generated by Prometheus AI are simulated
              and do not represent the views or beliefs of its creators.
            </p>
          </section>

          <section>
            <h2 className="font-black text-lg mb-2">5. Content Ownership and License</h2>
            <p className="font-bold">Your Inputs:</p>
            <p>
              You retain ownership of the prompts and content you submit. By submitting them, you grant us a worldwide, royalty-free,
              perpetual license to use, process, and store them for operating and improving the Service. You confirm that your inputs do not
              violate any third-party rights.
            </p>
            <p className="font-bold mt-2">Outputs:</p>
            <p>
              We own the Service’s underlying technology, models, and platform. You own the outputs generated for you, but you are granted
              only a limited, non-exclusive, non-transferable license to use them for personal, non-commercial purposes. Commercial use
              requires prior written permission.
            </p>
            <p className="mt-2">
              When sharing outputs publicly, you must disclose that they were AI-generated (e.g., “Generated by Prometheus AI”) — especially
              in political or public-facing contexts.
            </p>
            <p className="font-bold mt-2">Feedback:</p>
            <p>Any feedback, suggestions, or ideas you provide become our property without compensation.</p>
          </section>

          <section>
            <h2 className="font-black text-lg mb-2">6. AI Disclosures and Limitations</h2>
            <p className="mt-2">
              Transparency: All interactions occur with an AI system — not a human. Responses may contain inaccuracies, biases, fabricated
              information (“hallucinations”), or offensive content.
            </p>
            <p className="mt-2">No Professional Advice: Do not rely on Prometheus AI for professional or high-risk decisions.</p>
            <p className="mt-2">
              Political Content: Responses may express controversial or politically incorrect viewpoints. These are for debate and simulation
              purposes only and do not represent endorsements or verified facts.
            </p>
            <p className="mt-2">
              Compliance: You are responsible for complying with any laws or regulations regarding AI use, including disclosure requirements
              in political contexts.
            </p>
          </section>

          <section>
            <h2 className="font-black text-lg mb-2">7. Third-Party Content and Links</h2>
            <p>
              Prometheus AI may reference or link to third-party websites or content. We are not responsible for their accuracy, legality, or
              safety. Use them at your own risk.
            </p>
          </section>

          <section>
            <h2 className="font-black text-lg mb-2">8. Privacy and Data</h2>
            <p>
              Your use of Prometheus AI is subject to our Privacy Policy (coming soon). Prompts and responses may be collected and processed
              to improve the Service.
            </p>
            <p className="mt-2 font-bold">⚠️ Do not submit sensitive personal data. We are not responsible for any consequences resulting from the disclosure of such information.</p>
          </section>

          <section>
            <h2 className="font-black text-lg mb-2">9. Disclaimers</h2>
            <p>
              THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE” WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING
              MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
            </p>
            <p className="mt-2">We are not liable for:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Errors, inaccuracies, or omissions in outputs.</li>
              <li>Downtime or interruptions.</li>
              <li>User behavior or misuse of the Service.</li>
              <li>Emotional distress or harm caused by controversial or offensive content.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-black text-lg mb-2">10. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, we and our collaborators shall not be liable for any indirect, incidental, special,
              consequential, or punitive damages (including loss of profits, data, or goodwill), even if advised of the possibility.
            </p>
            <p className="mt-2">
              Our total liability will not exceed the greater of $100 or the amount you paid to use the Service in the 12 months before the
              claim.
            </p>
          </section>

          <section>
            <h2 className="font-black text-lg mb-2">11. Indemnification</h2>
            <p>
              You agree to indemnify and hold us harmless from any claims, damages, or expenses (including legal fees) resulting from your
              inputs or use of outputs, your violation of these Terms, or any infringement of third-party rights.
            </p>
          </section>

          <section>
            <h2 className="font-black text-lg mb-2">12. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service without notice if you violate these Terms. Upon termination, your
              license to use the Service ends. Provisions on ownership, liability, and indemnification will continue to apply.
            </p>
          </section>

          <section>
            <h2 className="font-black text-lg mb-2">13. Changes to These Terms</h2>
            <p>
              We may update these Terms periodically. Continued use of the Service after any changes indicates your acceptance of the updated
              Terms. We will notify you of significant updates via the Service or email.
            </p>
          </section>

          <section>
            <h2 className="font-black text-lg mb-2">15. Miscellaneous</h2>
            <p>Severability: If any provision is found invalid, the rest remain enforceable.</p>
            <p>No Waiver: Our failure to enforce any right is not a waiver of it.</p>
            <p>Assignment: We may assign these Terms without notice. You may not assign them without our written consent.</p>
            <p>Entire Agreement: These Terms and our Privacy Policy make up the entire agreement between you and us regarding the Service.</p>
            <p className="mt-2">Contact: <a className="underline" href="mailto:prometheushq@protonmail.com">prometheushq@protonmail.com</a></p>
          </section>

          <p className="mt-6 font-bold">
            By using Prometheus AI, you confirm that you have read, understood, and agreed to these Terms of Service.
          </p>
        </div>
      </div>
    </div>
  )
}


